```{r}

```

---
title: "sims"
format: html
editor: visual
---

## sims

```{r}
library(BAS)
```


```{r}
match.model = function(pop, methods, df.m) {
  m = length(methods)
  for (i in 1:m) {
    sample = methods[[i]] 
    marg.pop = pop$logmarg + log(pop$priorprobs)
    marg.sample = sample$logmarg + log(sample$priorprobs)
    loc = match( marg.sample, marg.pop)
    df.m[loc, i+1] = sample$postprobs
  }
  return(df.m)
}

bias = function(yhat, ytrue) {
  diff = abs(yhat -ytrue)
  mean(diff, na.rm = TRUE)
}

mse= function(yhat, ytrue) {
  diff = (yhat -ytrue)^2
  mean(diff, na.rm = TRUE)
}


IHT.wts = function(obj) {
  N.MC = eval(obj$call$MCMC.iterations)
  inc.prob = 1 - (1 - obj$sampleprobs)^N.MC
  rank.order = order(inc.prob)
  n = length(inc.prob)
  K = max((1:n)[inc.prob[rank.order] < 1/(1 + 1:n)])
  thresh = (inc.prob[rank.order])[K]
  inc.prob[inc.prob < thresh] = thresh
  w = exp(obj$logmarg + log(obj$priorprobs))/inc.prob 
  pp = w = w/sum(w)
  models = which.matrix(obj$which, obj$n.vars)
  probne0 = t(models) %*% pp
  return(list(postprobs = pp, probne0 = probne0, inc.prob = inc.prob))
}

pp.IHT = IHT.wts(tecator.IS)

HH.wts = function(obj) {
  ni = obj$freq
  inc.prob =  obj$sampleprobs
  w = ni*exp(obj$logmarg + log(obj$priorprobs))/inc.prob 
  pp = w = w/sum(w)
  models = which.matrix(obj$which, obj$n.vars)
  probne0 = t(models) %*% pp
  return(list(postprobs = pp, probne0 = probne0, inc.prob = inc.prob))
}

pp.HH = HH.wts(tecator.IS)
```



```{r}

data(UScrime, package="MASS")
#UScrime[,-2] = log(UScrime[,-2])
set.seed(42)
crime.amcmc =  bas.lm(log(y) ~ log(M) + So + log(Ed) + log(Po1) + log(Po2)
                    + log(LF) + log(M.F) + log(Pop) + log(NW) +
                      log(U1) + log(U2) + log(GDP) + log(Ineq) + log(Prob)+
                      log(Time), 
                    data=UScrime, n.models=2^15, prior="BIC", 
                    method = "AMCMC", burnin.iteration = 5000, 
                    MCMC.iterations = 5000, thin = 15, delta = .01, importance.sampling = FALSE, 
                    renormalize = FALSE)

plot(crime.amcmc$sampleprobs, crime.amcmc$postprobs.MCMC)
abline(0,1)

set.seed(42)
crime.ais =  bas.lm(log(y) ~ log(M) + So + log(Ed) + log(Po1) + log(Po2)
                      + log(LF) + log(M.F) + log(Pop) + log(NW) +
                        log(U1) + log(U2) + log(GDP) + log(Ineq) + log(Prob)+
                        log(Time), 
                      data=UScrime, n.models=2^15, prior="BIC", 
                      method = "AMCMC", burnin.iteration = 5000, 
                      MCMC.iterations = 5000, thin = 15, delta = .01, importance.sampling = TRUE)

plot(crime.ais$sampleprobs, crime.ais$postprobs.RN)
abline(0,1)

set.seed(42)
crime.mcmc = bas.lm(log(y) ~ log(M) + So + log(Ed) + log(Po1) + log(Po2)
                    + log(LF) + log(M.F) + log(Pop) + log(NW) +
                      log(U1) + log(U2) + log(GDP) + log(Ineq) + log(Prob)+
                      log(Time), 
                    data=UScrime, n.models=2^15, prior="BIC", 
                    method = "MCMC", burnin.iteration = 5000, 
                    MCMC.iterations = 5000, thin = 15, delta = .01, renormalize = FALSE)

plot(crime.mcmc$postprobs.MCMC, crime.mcmc$postprobs.RN)
abline(0,1)

crime.det = bas.lm(log(y) ~ log(M) + So + log(Ed) + log(Po1) + log(Po2)
                   + log(LF) + log(M.F) + log(Pop) + log(NW) +
                     log(U1) + log(U2) + log(GDP) + log(Ineq) + log(Prob)+
                     log(Time), 
                   data=UScrime, n.models=2^15, prior="BIC", 
                   method = "deterministic")
 
df = data.frame(TRUTH=crime.det$probne0.RN,AIS = crime.ais$probne0.RN, AMCMC=crime.ais$probne0.MCMC, 
                MCMC=crime.mcmc$probne0.MCMC)                  
plot(df)
cor(df)




df.m = data.frame(TRUTH = crime.det$postprobs.RN, AIS=NA, AMCMC=NA, MCMC=NA)
df.mod = match.model(crime.det, list(crime.ais, crime.amcmc, crime.mcmc), df.m)
plot(df.mod)

```

```{r}
data(tecator, package="FuncNN")
# Extract data and target
X <- tecator$absorp.fdata$data[1:172,]
fat <- tecator$y$Fat[1:172] 
data = data.frame(fat, X)

subsamp = seq(1,100, by=5)
p = length(subsamp)
b.it = 2000000
mc.it = 2000000
n.models = 2^15
```

```{r}
#| eval: FALSE

set.seed(42)


system.time(tecator.det <- bas.lm(fat ~ ., data=data[, c(subsamp,101)], prior="g-prior", 
                                  alpha = 100,
                      method = "deterministic", thin = 100,
                      burnin.iterations = b.it,
                      MCMC.iterations = mc.it,
                      delta = 0.01, n.models = 2^p))



tecator.probne0 = data.frame(TRUTH=tecator.det$probne0)
```

```{r}
#| eval: FALSE
load("tecator-probs-truth.dat")
load("tecator-det.Rdata")
```

```{r}
NSIM = 25

time = matrix(NA, nrow = NSIM, ncol=3)
for (t in 1:NSIM) {
  time[t,2] = system.time(bas.lm(fat ~ ., data=data[, c(subsamp,101)], prior="g-prior", 
                     alpha = 100, method = "AMCMC", 
                     burnin.iterations = b.it, thin = 100,
                     MCMC.iterations = mc.it, lambda = 102,
                     delta = 0.01, n.models = n.models, importance.sampling = FALSE))[3]
  time[t,3] = system.time(bas.lm(fat ~ ., data=data[, c(subsamp,101)], prior="g-prior", 
                      alpha = 100, method = "MCMC", 
                     burnin.iterations = b.it, thin = 100,
                     MCMC.iterations = mc.it,
                     delta = 0.01, n.models = n.models))[3]
  time[t,1] = system.time(bas.lm(fat ~ ., data=data[, c(subsamp,101)], prior="g-prior", 
                     alpha = 100, method = "AMCMC", 
                     burnin.iterations = b.it, thin=100,
                     MCMC.iterations = mc.it,  lambda = 102, # renormalize = TRUE,
                     delta = 0.01, n.models = n.models, importance.sampling = TRUE))[3]

print(time[t,])
}

colnames(time) <- c("HT", "AMCMC", "MCMC")
save(list=c("time"), file="tecator-time.dat")
```


```{r}
NSIM = 100
n.models = round(.05*2^p)

time = matrix(NA, nrow = NSIM, ncol=3)
bias.pip = matrix(NA, nrow = NSIM, ncol=3)
mse.pip = matrix(NA, nrow = NSIM, ncol=3)

bias.pp = matrix(NA, nrow = NSIM, ncol=3)
mse.pp = matrix(NA, nrow = NSIM, ncol=3)

set.seed(42)
for (i in 1:NSIM) {
print(i)
time[i, 1] = system.time(tecator.IS <- bas.lm(fat ~ ., data=data[, c(subsamp,101)], prior="g-prior", alpha = 100, 
                     method = "AMCMC", 
                     burnin.iterations = b.it, thin=100,
                     MCMC.iterations = mc.it,  lambda = 102, # renormalize = TRUE,
                     delta = 0.01, n.models = mc.it, importance.sampling = TRUE)
)[2]

time[i,2] = system.time(tecator.amc <- bas.lm(fat ~ ., data=data[, c(subsamp,101)], prior="g-prior", alpha = 100, 
                     method = "AMCMC", 
                     burnin.iterations = b.it, thin = 100,
                     MCMC.iterations = mc.it, lambda = 102,
                     delta = 0.01, n.models = n.models, importance.sampling = FALSE)
)[2]


time[i,3] = system.time(tecator.mcmc <- bas.lm(fat ~ ., data=data[, c(subsamp,101)],
                                               prior="g-prior", 
                      alpha = 100, method = "MCMC", 
                     burnin.iterations = b.it, thin = 100,
                     MCMC.iterations = mc.it,
                     delta = 0.01, n.models = n.models)
)[2]

tecator.probne0$HT <- tecator.IS$probne0
tecator.probne0$AMC <-  tecator.amc$probne0.MCMC
tecator.probne0$MCMC <-tecator.mcmc$probne0.MCMC


bias.pip[i, ] <- apply(tecator.probne0,2, bias, tecator.probne0$TRUTH)[-1]
mse.pip[i, ] <- apply(tecator.probne0,2, mse, tecator.probne0$TRUTH)[-1]


df.mod = data.frame(TRUTH = tecator.det$postprobs.RN, AIS=NA, AMCMC=NA, MCMC=NA)
tecator.modelprobs = match.model(tecator.det, list(tecator.IS, tecator.amc, tecator.mcmc), df.mod)

bias.pp[i,] <- apply(tecator.modelprobs,2, bias, tecator.modelprobs$TRUTH)[-1]
mse.pp[i,] <- apply(tecator.modelprobs,2, mse, tecator.modelprobs$TRUTH)[-1]
print(mse.pip[i,])
print(time[i,])
}
```
```{r}
out = which(mse.pp[,2] == max(mse.pp[,2]))
mse.pp = mse.pp[-out,]
mse.pip = mse.pip[-out,]
bias.pp = bias.pp[-out,]
bias.pip = bias.pip[-out,]
```

```{r}
boxplot(mse.pp*1e7)
```


```{r}
boxplot(mse.pip*1e3)
```


```{r}
boxplot(bias.pp)
```


```{r}
boxplot(bias.pip)
```
```{r}
plot.modprobs = function(x,y, ...) {
  df = data.frame(x, y)
  df = df[!is.na(y),]
  plot(df, ...)
  abline(0,1)
}
```

```{r}
plot.modprobs(tecator.modelprobs$AIS, tecator.modelprobs$TRUTH, xlab="TRUE", ylab = "AIS")

plot(tecator.modelprobs)
cor(tecator.modelprobs, use = "pair")
```

